spring.application.name=CoreCommerce
spring.datasource.username=postgres
spring.datasource.password=diogo123
spring.datasource.url=jdbc:postgresql://localhost/CoreCommerce
server.port=8080
spring.jpa.hibernate.ddl-auto=update
